In [14]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
import seaborn as sns
sns.set()

In [3]:
data1 = pd.read_csv("imputed_dataset_1.csv", engine='python')
data1.head()
data2 = pd.read_csv("imputed_dataset_2.csv", engine='python')
data2.head()
data3 = pd.read_csv("imputed_dataset_3.csv", engine='python')
data3.head()
data4 = pd.read_csv("imputed_dataset_4.csv", engine='python')
data4.head()
data5 = pd.read_csv("imputed_dataset_5.csv", engine='python')
data5.head()

Unnamed: 0  weight_16   height_16  comp_noint_bed_16  comp_int_bed_16  \
0           0  59.294132  181.602831                0.0              0.0   
1           1  62.290242  168.453878                0.0              0.0   
2           2  62.290242  168.453878                0.0              0.0   
3           3  49.812426  160.224186                0.0              0.0   
4           4  62.270030  191.703227                1.0              0.0   

   talk_phon_wend  text_wend  talk_mob_wend  comp_wend  musi_wend  ...  \
0             1.0        1.0            1.0        2.0        0.0  ...   
1             1.0        1.0            1.0        2.0        0.0  ...   
2             1.0        1.0            1.0        2.0        0.0  ...   
3             1.0        2.0            1.0        2.0        0.0  ...   
4             0.0        0.0            0.0        1.0        0.0  ...   

   anx_band_15  exercise  child_bull  has_dep_diag  secd_diag  prim_diag  \
0          0.5       4.0         0.0           0.0        0.0        0.0   
1          3.0       3.0         0.0           0.0        1.0        1.0   
2          3.0       3.0         0.0           0.0        1.0        1.0   
3          3.0       3.0         0.0           0.0        0.0        1.0   
4          3.0       3.0         0.0           0.0        1.0        1.0   

   panic_score  dep_thoughts  dep_score  comp_house  
0          0.0           1.0        0.0         1.0  
1          0.0           3.0        1.0         0.0  
2          0.0           3.0        1.0         0.0  
3          0.0           2.0        0.0         0.0  
4          0.0           3.0        0.0         0.0  

[5 rows x 43 columns]

In [22]:
Y = np.column_stack((data5['has_dep_diag'], data5['secd_diag'], data5['prim_diag'], data5['dep_score'], data5['dep_thoughts']))
print(Y.shape)
X = data5.drop(['has_dep_diag'],axis=1).drop(['secd_diag'],axis=1).drop(['prim_diag'],axis=1).drop(['dep_score'],axis=1).drop(['dep_thoughts'],axis=1)
print(X.shape)

(13734, 5)
(13734, 38)


In [23]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y,test_size=0.2, random_state=40)
print(X_train.shape); print(X_test.shape)
print(y_train.shape); print(y_test.shape)

(10987, 38)
(2747, 38)
(10987, 5)
(2747, 5)


In [24]:
#reduce the dataset
X_train_reduced, y_train_reduced = X_train[0:1000], y_train[0:1000]
X_test_reduced, y_test_reduced = X_test[0:200], y_test[0:200]
print(X_train_reduced.shape); print(X_test_reduced.shape)
print(y_train_reduced.shape); print(y_test_reduced.shape)

(1000, 38)
(200, 38)
(1000, 5)
(200, 5)


In [25]:
knn = KNeighborsClassifier(n_neighbors=5) #, metric='euclidean')
knn.fit(X_train, y_train)

KNeighborsClassifier()

In [26]:
y_pred = knn.predict(X_test)

In [27]:
print(confusion_matrix(y_test.ravel(), y_pred.ravel()))

[[3367 2239    6    4    1    0    0    0    0    0    0    0    0]
 [ 408 4496   87  497    0    0    0    0    0    0    0    0    0]
 [  74  407   54  382    0    0    0    0    0    0    0    0    0]
 [  34  151   48 1195    0    0    0    0    0    0    0    0    0]
 [  15   45    8   36    0    0    0    0    0    0    0    0    0]
 [   9   29    4    5    0    0    0    0    0    0    0    0    0]
 [   7    9    0    0    0    0    0    0    0    0    0    0    0]
 [   0    1    0    0    0    0    0    0    0    0    0    0    0]
 [   6   21    0    0    0    0    0    0    0    0    0    0    0]
 [   5    4    0    0    0    0    0    0    0    0    0    0    0]
 [   5   17    0    0    0    0    0    0    0    0    0    0    0]
 [  13   25    0    0    0    0    0    0    0    0    0    0    0]
 [   4   17    0    0    0    0    0    0    0    0    0    0    0]]


In [28]:
print(classification_report(y_test.ravel(), y_pred.ravel()))

              precision    recall  f1-score   support

         0.0       0.85      0.60      0.70      5617
         1.0       0.60      0.82      0.69      5488
         2.0       0.26      0.06      0.10       917
         3.0       0.56      0.84      0.67      1428
         4.0       0.00      0.00      0.00       104
         5.0       0.00      0.00      0.00        47
         6.0       0.00      0.00      0.00        16
         7.0       0.00      0.00      0.00         1
         8.0       0.00      0.00      0.00        27
         9.0       0.00      0.00      0.00         9
        10.0       0.00      0.00      0.00        22
        11.0       0.00      0.00      0.00        38
        12.0       0.00      0.00      0.00        21

    accuracy                           0.66     13735
   macro avg       0.18      0.18      0.17     13735
weighted avg       0.67      0.66      0.64     13735



/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _wa